export const achievements = [
  {
    _id: 'runcode-25',
    icon: '',
    goal: 25,
    description: 'Run your code 25 times',
    progress: 0,
  },
  {
    _id: 'runcode-50',
    icon: '',
    goal: 50,
    description: 'Run your code 50 times',
    progress: 0,
  },
  {
    _id: 'runcode-75',
    icon: '',
    goal: 75,
    description: 'Run your code 75 times',
    progress: 0,
  },
  {
    _id: 'runcode-100',
    icon: '',
    goal: 100,
    description: 'Run your code 100 times',
    progress: 0,
  },
  {
    _id: 'runcode-150',
    icon: '',
    goal: 150,
    description: 'Run your code 150 times',
    progress: 0,
  },
  {
    _id: 'runcode-200',
    icon: '',
    goal: 200,
    description: 'Run your code 200 times',
    progress: 0,
  },
  {
    _id: 'runcode-300',
    icon: '',
    goal: 300,
    description: 'Run your code 300 times',
    progress: 0,
  },
  {
    _id: 'runcode-400',
    icon: '',
    goal: 400,
    description: 'Run your code 400 times',
    progress: 0,
  },
  {
    _id: 'runcode-500',
    icon: '',
    goal: 500,
    description: 'Run your code 500 times',
    progress: 0,
  },
  {
    _id: 'hours-2',
    icon: '',
    goal: 2,
    description: 'Complete 2 hours of learning',
    progress: 0,
  },
  {
    _id: 'hours-4',
    icon: '',
    goal: 4,
    description: 'Complete 4 hours of learning',
    progress: 0,
  },
  {
    _id: 'hours-6',
    icon: '',
    goal: 6,
    description: 'Complete 6 hours of learning',
    progress: 0,
  },
  {
    _id: 'hours-8',
    icon: '',
    goal: 8,
    description: 'Complete 8 hours of learning',
    progress: 0,
  },
  {
    _id: 'hours-10',
    icon: '',
    goal: 10,
    description: 'Complete 10 hours of learning',
    progress: 0,
  },
  {
    _id: 'exercises-10',
    icon: '',
    goal: 10,
    description: 'Complete 10 exercises',
    progress: 0,
  },
  {
    _id: 'exercises-25',
    icon: '',
    goal: 25,
    description: 'Complete 25 exercises',
    progress: 0,
  },
  {
    _id: 'exercises-50',
    icon: '',
    goal: 50,
    description: 'Complete 50 exercises',
    progress: 0,
  },
  {
    _id: 'exercises-75',
    icon: '',
    goal: 75,
    description: 'Complete 75 exercises',
    progress: 0,
  },
  {
    _id: 'exercises-100',
    icon: '',
    goal: 100,
    description: 'Complete 100 exercises',
    progress: 0,
  },
  {
    _id: 'exercises-150',
    icon: '',
    goal: 150,
    description: 'Complete 150 exercises',
    progress: 0,
  },
  {
    _id: 'exercises-200',
    icon: '',
    goal: 200,
    description: 'Complete 200 exercises',
    progress: 0,
  },
  {
    _id: 'exercises-255',
    icon: '',
    goal: 255,
    description: 'Complete 255 exercises',
    progress: 0,
  },
  {
    _id: 'challenges-5',
    icon: '',
    goal: 5,
    description: 'Complete 5 challenges',
    progress: 0,
  },
  {
    _id: 'challenges-10',
    icon: '',
    goal: 10,
    description: 'Complete 10 challenges',
    progress: 0,
  },
  {
    _id: 'challenges-20',
    icon: '',
    goal: 20,
    description: 'Complete 20 challenges',
    progress: 0,
  },
  {
    _id: 'challenges-30',
    icon: '',
    goal: 30,
    description: 'Complete 30 challenges',
    progress: 0,
  },
  {
    _id: 'challenges-40',
    icon: '',
    goal: 40,
    description: 'Complete 40 challenges',
    progress: 0,
  },
  {
    _id: 'challenges-50',
    icon: '',
    goal: 50,
    description: 'Complete 50 challenges',
    progress: 0,
  },
  {
    _id: 'projects-5',
    icon: '',
    goal: 5,
    description: 'Complete 5 projects',
    progress: 0,
  },
  {
    _id: 'projects-10',
    icon: '',
    goal: 10,
    description: 'Complete 10 projects',
    progress: 0,
  },
  {
    _id: 'projects-15',
    icon: '',
    goal: 15,
    description: 'Complete 15 projects',
    progress: 0,
  },
  {
    _id: 'projects-20',
    icon: '',
    goal: 20,
    description: 'Complete 20 projects',
    progress: 0,
  },
  {
    _id: 'projects-25',
    icon: '',
    goal: 25,
    description: 'Complete 25 projects',
    progress: 0,
  },
  {
    _id: 'quizzes-5',
    icon: '',
    goal: 5,
    description: 'Complete 5 quizzes',
    progress: 0,
  },
  {
    _id: 'quizzes-10',
    icon: '',
    goal: 10,
    description: 'Complete 10 quizzes',
    progress: 0,
  },
  {
    _id: 'quizzes-15',
    icon: '',
    goal: 15,
    description: 'Complete 15 quizzes',
    progress: 0,
  },
  {
    _id: 'quizzes-20',
    icon: '',
    goal: 20,
    description: 'Complete 20 quizzes',
    progress: 0,
  },
  {
    _id: 'courses-1',
    icon: '',
    goal: 1,
    description: 'Complete 1 course',
    progress: 0,
  },
  {
    _id: 'daysrow-7',
    icon: '',
    goal: 7,
    description: 'Login in to the platform 7 days in a row',
    progress: 0,
  },
  {
    _id: 'daysrow-30',
    icon: '',
    goal: 30,
    description: 'Login in to the platform 30 days in a row',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-5',
    icon: '',
    goal: 5,
    description: 'Unlocking 5 achievements',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-10',
    icon: '',
    goal: 10,
    description: 'Unlocking 10 achievements',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-15',
    icon: '',
    goal: 15,
    description: 'Unlocking 15 achievements',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-20',
    icon: '',
    goal: 20,
    description: 'Unlocking 20 achievements',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-25',
    icon: '',
    goal: 25,
    description: 'Unlocking 25 achievements',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-30',
    icon: '',
    goal: 30,
    description: 'Unlocking 30 achievements',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-35',
    icon: '',
    goal: 35,
    description: 'Unlocking 35 achievements',
    progress: 0,
  },
  {
    _id: 'unlock-achieve-40',
    icon: '',
    goal: 40,
    description: 'Unlocking 40 achievements',
    progress: 0,
  },
];
