//---------------> GLOBAL TYPES
export const UPDATE_APP_STATE = "UPDATE_APP_STATE";
export const UPDATE_APP_TOKEN = "UPDATE_APP_TOKEN";
export const UPDATE_APP_LOCALE = "UPDATE_APP_LOCALE";
export const UPDATE_APP_MODE = 'UPDATE_APP_MODE';
export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const CLEAR_STATE = 'CLEAR_STATE';
export const API_VERSION_STATE = 'API_VERSION_STATE';


//---------------> TYPES OF LOGIN
export const LOGIN_EMAIL_CHANGED = 'login_email_changed';
export const LOGIN_PASSWORD_CHANGED = 'login_password_changed';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const SHOW_LOGIN_ALERT = "SHOW_LOGIN_ALERT"; 

export const SEND_EMAIL = 'send_email';
export const SEND_EMAIL_SUCCESS = 'send_email_success';
export const SEND_EMAIL_FAIL = 'send_email_fail';
export const RESET_FORGOT_PASSWORD_ERRORS = 'RESET_FORGOT_PASSWORD_ERRORS';
export const RESET_INFO = 'RESET_INFO';
export const FORGOT_PASSWORD_CHANGED = 'FORGOT_PASSWORD_CHANGED';
export const SAVE_TROUBLED_EMAIL = 'SAVE_TROUBLED_EMAIL';
export const IS_LOGIN_LODING = 'IS_LOGIN_LODING';

//---------------> TYPES OF SIGNUP
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL'
export const SIGN_UP_EMAIL_CHANGED = 'SIGN_UP_EMAIL_CHANGED'
export const SIGN_UP_PASSWORD_CHANGED = 'SIGN_UP_PASSWORD_CHANGED'
export const SIGN_UP_CONFIRM_PASSWORD_CHANGED = 'SIGN_UP_CONFIRM_PASSWORD_CHANGED'
export const RESET_SIGNUP = 'RESET_SIGNUP';
export const RESET_ERROR_STATE = 'RESET_ERROR_STATE';
export const SIGNUP_PUBLIC_USER_FAIL = "SIGNUP_PUBLIC_USER_FAIL";
export const RESET_SIGNUP_ERRORS = "RESET_SIGNUP_ERRORS";

//---------------> TYPES OF PROFILE
export const TAKE_PHOTO = 'TAKE_PHOTO';
export const UPDATE_USER_PHOTO = 'UPDATE_USER_PHOTO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SAVE_PHOTO = 'SAVE_PHOTO';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';
export const UPDATE_USER_PHOTO_FAIL = 'UPDATE_USER_PHOTO_FAIL';
export const PROFILE_IS_LOADING = 'PROFILE_IS_LOADING';
export const PROFILE_FIRSTNAME_CHANGED = "PROFILE_FIRSTNAME_CHANGED";
export const PROFILE_LASTNAME_CHANGED = "PROFILE_LASTNAME_CHANGED";
export const PROFILE_USERNAME_CHANGED = "PROFILE_USERNAME_CHANGED";
export const PROFILE_PASSWORD_CHANGED = "PROFILE_PASSWORD_CHANGED";
export const PROFILE_CONFIRM_PASSWORD_CHANGED = "PROFILE_CONFIRM_PASSWORD_CHANGED";
export const LOAD_REWARDS = "LOAD_REWARDS";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const PROFILE_PASSWORD_CHANGED_SUCCESS = "PROFILE_PASSWORD_CHANGED_SUCCESS";
export const PROFILE_PASSWORD_CHANGED_FAIL = "PROFILE_PASSWORD_CHANGED_FAIL";
export const PROFILE_CONFIRM_PASSWORD_CHANGED_SUCESS = "PROFILE_CONFIRM_PASSWORD_CHANGED_SUCESS";
export const PROFILE_CONFIRM_PASSWORD_CHANGED_FAIL = "PROFILE_CONFIRM_PASSWORD_CHANGED_FAIL";
export const RESET_PROFILE_ERRORS = "RESET_PROFILE_ERRORS";

//---------------> TYPES OF SHOW THE NEW FEATURES
export const SHOW_FEATURES = 'SHOW_NEW_FEATURES';

//---------------> TYPES OF LOGOUT
export const LOGOUT = 'LOGOUT';

//---------------> TYPES DASHBOARD
export const LOADING_CLASSES_INFO = 'LOADING_CLASSES_INFO';
export const LOAD_USER_CLASSES = 'LOAD_USER_CLASSES';
export const LOAD_CLASSES_FAIL = 'LOAD_USER_FAIL';
export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const LOAD_USER_LAST_CLASS = 'LOAD_USER_LAST_CLASS';
export const SHOW_PURCHASE_SCREEN = 'SHOW_PURCHASE_SCREEN';
export const RESET_VERIFY_LOG_LOGIN = 'RESET_VERIFY_LOG_LOGIN';
export const SEARCH_IN_PROGRESS_CURRICULUMS = 'SEARCH_IN_PROGRESS_CURRICULUMS';
export const SEARCH_AVAILABLE_CURRICULUMS = 'SEARCH_AVAILABLE_CURRICULUMS';
export const SEARCH_COMPLETED_CURRICULUMS = 'SEARCH_COMPLETED_CURRICULUMS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const LOAD_CURRICULUMS = 'LOAD_CURRICULUMS';
export const ERROR_LOADING_CURRICULUMS = 'ERROR_LOADING_CURRICULUMS';
export const NEW_ITEMS_COUNT = 'NEW_ITEMS_COUNT';
export const ACHIEVEMENT_OVERALL_PROGRESS = 'ACHIEVEMENT_OVERALL_PROGRESS';
export const TAB_SELECTED = 'TAB_SELECTED';
export const KEYBOARD_OPEN = "KEYBOARD_OPEN";

export const ENROLL_MORE_INFO__CLASS = 'ENROLL_MORE_INFO__CLASS';
export const SUCCESS_MORE_INFO_ENROLLING_CLASS = 'SUCCESS_MORE_INFO_ENROLLING_CLASS';
export const ERROR_MORE_INFO_ENROLLING_CLASS = 'ERROR_MORE_INFO_ENROLLING_CLASS';
export const RESET_MORE_INFO_ENROLL_CLASS = 'RESET_MORE_INFO_ENROLL_CLASS';

//---------------> TYPES AVAILABLE CURRICULUMS
export const SUCCESS_ENROLLING_CLASS = 'SUCCESS_ENROLLING_CLASS';
export const ERROR_ENROLLING_CLASS = 'ERROR_ENROLLING_CLASS';
export const ENROLL_CLASS = 'ENROLL_CLASS';
export const RESET_ENROLL_CLASS = 'RESET_ENROLL_CLASS';

//---------------> TYPES COMPLETED CURRICULUMS
export const LOAD_COMPLETED_CLASSES = 'LOAD_COMPLETED_CLASSES'

//---------------> TYPES OF CURRICULUMINFO
export const SET_CLASS_INTERFACE_DATA = 'SET_CLASS_INTERFACE_DATA';
export const CURRICULUMINFO_IS_LOADING = 'CURRICULUMINFO_IS_LOADING';

//---------------> TYPES OF CERTIFICATE
export const IS_LOADING_CERTIFICATE = 'IS_LOADING_CERTIFICATE';
export const SHOW_CERTIFICATE = 'SHOW_CERTIFICATE';
export const CLEAR_CERTIFICATE_DATA = 'CLEAR_CERTIFICATE_DATA';

//---------------> TYPES OF SUPPORT
export const SUPPORT_IS_BUSY = 'SUPPORT_IS_BUSY';
export const SUCCESS_SUPPORT_CREDENTIALS = 'SUCCESS_CREDENTIALS';
export const ERROR_SUPPORT_CREDENTIALS = 'ERROR_CREDENTIALS';
export const RESET_ERROR_CREDENTIALS = 'RESET_ERROR_CREDENTIALS';
export const JOINING_ROOM = 'JOINING_ROOM';
export const WAITING_FOR_TECH_SUPPORT = 'WAITING_FOR_TECH_SUPPORT';
export const TECH_ENTER_THE_ROOM = 'TECH_ENTER_THE_ROOM';
export const TECH_SUPPORT_IS_TYPING = 'TECH_SUPPORT_IS_TYPING';
export const MESSAGE = 'MESSAGE';
export const RESET_SUPPORT = 'RESET_SUPPORT';
export const TECH_LEFT_CHAT = 'TECH_LEFT_CHAT';
export const USER_IN_CHAT_ROOM = 'USER_IN_CHAT_ROOM';
export const UPDATE_TECH_IMAGE = 'UPDATE_TECH_IMAGE';
export const UPDATE_USER_SUPPORT_IMAGE = 'UPDATE_USER_SUPPORT_IMAGE';

//---------------> TYPES OF COURSE
export const SET_CLASS_LIST_DATA = 'SET_CLASS_LIST_DATA';
export const SET_EXERCISE_DATA = 'SET_EXERCISE_DATA';
export const EXERCISE_IS_LOADING = 'EXERCISE_IS_LOADING';
export const CLASS_ID = 'CLASS_ID';
export const SET_ROOM_ID = 'SET_ROOM_ID';
export const COURSE_CURRICULUM_ID = 'COURSE_CURRICULUM_ID';
export const ON_RUNSCRIPT_ERROR = 'ON_RUNSCRIPT_ERROR';
export const ON_VALIDATION = 'ON_VALIDATION';
export const RESET_RESPONSE = 'RESET_RESPONSE';
export const HIDE_ERROR_VALIDATION = 'HIDE_ERROR_VALIDATION';
export const TRIAL_MODE_COUNT_VIDEO = 'TRIAL_MODE_COUNT_VIDEO';
export const SHOW_AD = 'SHOW_AD';
export const HIDE_AD = 'HIDE_AD';
export const SHOW_NEXT_BUTTON = "SHOW_NEXT_BUTTON";
export const CLEAR_CLASS_INTERFACE_DATA = 'CLEAR_CLASS_INTERFACE_DATA';
export const COMPLETED_VIDEO = "COMPLETED_VIDEO";
export const STATE_SUBTITLES = "STATE_SUBTITLES";
export const CURRENT_ENLAPSED_TIME = "ENLAPSED_TIME";
export const SAVE_VIDEO_CURRENTTIME= "SAVE_VIDEO_CURRENTTIME";
export const RESET_VIDEO_CURRENTTIME= "RESET_VIDEO_CURRENTTIME";
export const SET_SIDE_MENU_STATE= "SET_SIDE_MENU_STATE";
export const QUIZ_FINISHED= "QUIZ_FINISHED";
export const QUIZ_STATUS = "QUIZ_STATUS";
export const RESET_QUIZ_STATUS = "RESET_QUIZ_STATUS";
export const BUTTON_ANIMATED = "BUTTON_ANIMATED";

//---------------> TYPES OF ACHIEVEMENTS
export const SET_ACHIEVEMENT_LIST = 'SET_ACHIEVEMENT_LIST';
export const ACHIEVEMENTS_LOADING = 'ACHIEVEMENTS_LOADING';

//---------------> TYPES OF EVENT
export const SET_EVENT_DATA = 'SET_EVENT_DATA';
export const SET_EVENT_REWARD = 'SET_EVENT_REWARD';
export const EVENT_LOADING = 'EVENT_LOADING';

//---------------> TYPES OF SUBSCRIPTION
export const SUBSCRIPTION_LOADING = 'SUBSCRIPTION_LOADING';
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_FAIL = 'SUBSCRIPTION_FAIL';
export const SUBSCRIPTION_RESET = 'SUBSCRIPTION_RESET';
